from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.exc import OperationalError
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

DATABASE_URL = "postgresql://postgres:1@localhost:5433/django2"

Base = declarative_base()
try:
    engine = create_engine(DATABASE_URL)
    with engine.connect():
        print("Connected to PostgreSQL successfully!")
except OperationalError as e:
    print(f"Failed to connect to PostgreSQL: {e}")
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)




class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, unique=True, index=True)
    username = Column(String, index=True)


Base.metadata.create_all(bind=engine)
