version: '3.8'

services:
  bot:
    build: .
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - API_TOKEN='7023961169:AAH9r3DW0KGgtBg7BKlWQ9vgCdp8doKYa-s'
    volumes:
      - .:/app

  celery_worker:
    build: .
    command: celery -A celery_app worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - API_TOKEN='7023961169:AAH9r3DW0KGgtBg7BKlWQ9vgCdp8doKYa-s'
    volumes:
      - .:/app

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
